### ISSUE TITLE
Error installing Linux Error downloading the virtual machine. Please try again.

### ISSUE THREAD

**Issue by harshcans** [sebanc/brunch#1162]
" Error installing Linux
Error downloading the virtual machine. Please try again. "

This error is showing in my screen.

Brunch: r91 stable 20210620
ChromeOS image: rammus 91.0.4472.114

**Comment by bm-a** [comment]
> " Error installing Linux
> Error downloading the virtual machine. Please try again. "
> 
> This error is showing in my screen.
> 
> Brunch: r91 stable 20210620
> ChromeOS image: rammus 91.0.4472.114



Set this flag to “disabled”
By typing this in chrome

chrome://flags#crostini-use-dlc

Now
Reboot and try again

**Comment by harshcans** [comment]
Thank u @bm-a for this awesome reply .
" It's Work "

I have been trying tying theese from so many days.

**Comment by block6791** [comment]
> > " Error installing Linux
> > Error downloading the virtual machine. Please try again. "
> > This error is showing in my screen.
> > Brunch: r91 stable 20210620
> > ChromeOS image: rammus 91.0.4472.114
> 
> Set this flag to “disabled”
> By typing this in chrome
> 
> chrome://flags#crostini-use-dlc
> 
> Now
> Reboot and try again

Solved by disalbing this flag. Thanks for the helpful tip.

**Comment by yeahman45** [comment]
I am having the same error with [Brunch r101 stable 20220529]

chrome://flags#crostini-use-dlc
does not seem to solve the issue.

**Comment by King-Lucifer6** [comment]
Error installing Linux
Error downloading the virtual machine. Please try again.

ChromeOs Version 101.0.4951.59 (Official Build) (64-bit)
![image](https://user-images.githubusercontent.com/86183954/174424552-801534c0-6792-46ff-ae9e-20ebfe11b7a8.png)
and theres no #crostini-use-dlc in my ChromeOs.

Can anyone please help?

**Comment by ankur-connect** [comment]
Having the same issue @King-Lucifer6

**Comment by block6791** [comment]
I have the same issue.

**Comment by block6791** [comment]
I solved the issue. I set "enable updates" in the Brunch Framework options. I only set this option without actually upgrading. Then the Linux installation worked fine and is completely functional. I hope this helps others with this issue. This was done on Brunch + ChromeOS versions 102.

**Comment by ankur-connect** [comment]
Same here...I did some hit and trial in Brunch configuration and it worked!!

**Comment by SBShaown** [comment]
> I solved the issue. I set "enable updates" in the Brunch Framework options. I only set this option without actually upgrading. Then the Linux installation worked fine and is completely functional. I hope this helps others with this issue. This was done on Brunch + ChromeOS version 102.

I am having the same problem. Can you tell me how you fix that problem in more detail?
