### ISSUE TITLE
Update to Chrome 85 cause sound to be very quiet (Matebook X Pro)

### ISSUE THREAD

**Issue by steinano** [sebanc/brunch#516]
Sound has worked normally in Chrome 83, 84. In 84 it was quiet in Android but still works normally inside ChromeOS.
Same issue with both Brunch r83 k4.19 stable 20200708 and Brunch r85 k4.19 testing 20200905.

**Comment by volram** [comment]
Any solution? Something similar occurs with MacBook Pro 11,1. The Chromium team has updated the way audio functions in Chrome os.

**Comment by sebanc** [comment]
Unfortunately, the brunch framework is based on the prebuilt chromeos images and not chromiumos. As it is not built from source, I cannot apply such changes.

There are nevertheless probably other solutions to fix this issue (using alsa mixer / ucm files ...) but my knowledge on audio drivers is limited and I cannot reproduce this issue so someone would have to come up with a fix.

**Comment by sebanc** [comment]
Could you check if, by any chance, it has not been fixed in dev channel ?

**Comment by sebanc** [comment]
@volram Do you have a link to the chromium team discussions related to this ?

**Comment by volram** [comment]
https://chromium-review.googlesource.com/c/chromium/src/+/2181254

**Comment by sebanc** [comment]
We should be able to do something with "dbus-send" command using destination "org.chromium.cras" and setting the property name "MaxSupportedChannels" to 2. However, I don't really know how to use dbus-send yet.

If someone can help it would be great, else I will try to have a look at it later.

**Comment by sebanc** [comment]
Note for myself, to display audio settings:
`dbus-send --system --dest=org.chromium.cras --print-reply --type=method_call /org/chromium/cras org.chromium.cras.Control.GetNodes`

**Comment by sebanc** [comment]
Found here:
https://github.com/dnschneid/crouton/issues/654

**Comment by volram** [comment]
In my case, the HDMI output works as expected, but the internal speaker is muted.

**Comment by volram** [comment]
The good news is that in Chrome OS Canary Versão 87.0.4261.0 the sound is working again. The build is relatively stable (until recently it crashed everything). So, if someone wants some adventure...

**Comment by sebanc** [comment]
This issue has reportedly been fixed in the latest r85 stable chromeos update (a few days ago). Could you confirm it ?

**Comment by steinano** [comment]
I upgraded to latest 85 now and sound works again!

Still the same sound issue persists in Android apps, but that was the same in r83 and r84.
