### ISSUE TITLE
When I see the welcome GUI,it reboot.

### ISSUE THREAD

**Issue by ericma15** [sebanc/brunch#9]
First, thanks what you have done.
I use the script to build a image. And I boot it succesful.But everytime I saw chromeos welcome GUI,it sudden reboot.
I try use a usb disk and install on ssd. But nothing change.
I have tried these three images, eve,nocturne and octpus , nothing change.
And also I use chromefy build a image can succes boot and use with everything ok with image eve.

**Comment by sebanc** [comment]
Thank you. Could you please provide me with your computer model ? Does it have dual i915/nvidia gpu ?

**Comment by ericma15** [comment]
> Thank you. Could you please provide me with your computer model ? Does it have dual i915/nvidia gpu ?

no,it's lenovo yoga 730 13-IWL with intel i5-8265u intel 640 graphic card,and a nvme ssd

**Comment by ericma15** [comment]
I've test with chromefy build ChromeOS, it fits well. All include pen and touchscreen worked well.

**Comment by sebanc** [comment]
When you chromefy, which kernel are you using, ATB or fydeos ?

**Comment by ericma15** [comment]
> When you chromefy, which kernel are you using, ATB or fydeos ?
both are okay, I built two. They all can work and perform well

**Comment by ericma15** [comment]
I use https://chromium.arnoldthebat.co.uk/special//Camd64OS_R78-12499.B-Vanilla.7z and fydeos stable

**Comment by sebanc** [comment]
Thanks for the additional information, I have an idea what the problem might be, I will try to correct it in my next build and inform you when it's out so that you can test.

**Comment by ericma15** [comment]
> Thanks for the additional information, I have an idea what the problem might be, I will try to correct it in my next build and inform you when it's out so that you can test.

Ok, thank you very much

**Comment by sebanc** [comment]
Hi, i just pushed 2 new releases (one with kernel 4.14 and one with kernel 4.19). Could you try them when you have the time ?

**Comment by ericma15** [comment]
> Hi, i just pushed 2 new releases (one with kernel 4.14 and one with kernel 4.19). Could you try them when you have the time ?

OK,I'll try it now.

**Comment by ericma15** [comment]
> Hi, i just pushed 2 new releases (one with kernel 4.14 and one with kernel 4.19). Could you try them when you have the time ?

No ,i try 4.19 with eve and octpus and 4.14 with octpus. It still have the problem.
I can see the brunch rebuild the fs.then screen shows chromeOS,when enter the setup page,before i try to click the button,it reboot.

**Comment by sebanc** [comment]
Thanks for testing, then the problem is not what i thought it was. I will keep looking into it.

**Comment by sebanc** [comment]
Could you try removing all files in the "patches" on partition 7 and reboot ? It would allow me to understand if the crash is related to the included patches.

**Comment by ericma15** [comment]
ok，i'll try it.

**Comment by ericma15** [comment]
The first time the screen sudden
 show some word like"factory mode
 " And a yellow "!". Then it reboot. Next time when boot to welcome page,it behave like I
Didn't remove patches.

**Comment by ericma15** [comment]
Is there a way I can see the log?

**Comment by sebanc** [comment]
Thanks for trying, it is the expected behaviour, it means it is not the patches.

Could you try to add "module_blacklist=hid-sensor-cros-compat" to the kernel command line in grub.cfg on partition 12 ?

**Comment by ericma15** [comment]
Unfortunately, still reboot.

**Comment by sebanc** [comment]
I don't see how we could get the log in that case...

**Comment by ericma15** [comment]
I use camera slow motion caputure the screen,before it show chromeos
 Screen. I see "NMI watch dog :enabled". Maybe watchdog?

**Comment by sebanc** [comment]
Could you try adding "nmi_watchdog=0" and if it does not work "fbcon=map:1" to the kernel command line ?

**Comment by ericma15** [comment]
> Could you try adding "nmi_watchdog=0" and if it does not work "fbcon=map:1" to the kernel command line ?

Both are reboot. When use last, the screen don't print anything.

**Comment by sebanc** [comment]
Chances are low but i just replaced the 4.19 release as the previous one had incorrect acpi patches, could you try it when you have some time ?

**Comment by ericma15** [comment]
> Chances are low but i just replaced the 4.19 release as the previous one had incorrect acpi patches, could you try it when you have some time ?

Ok,I'll try it tomorrow. Really thank you.you are a nice developer.

**Comment by sebanc** [comment]
Thanks, I hope we will manage to fix this. If I have other ideas, I will post them here but feel free to try them when you have the time.

**Comment by ericma15** [comment]
> Thanks, I hope we will manage to fix this. If I have other ideas, I will post them here but feel free to try them when you have the time.

It still reboot. I upload my img build with chromefy.here is the link https://drive.google.com/open?id=1Jkc-fIw-WFK8Zy--7GYGUfKEL8KOH8o2. I found the param is cros_efi and i915.modeset=1. I added it but nothing changed.

**Comment by sebanc** [comment]
Unfortunately, it seems the issue lies within the kernel so I cannot really use a croissant image to track it.
However, could you provide me with a "dmesg" and an "lsmod" from croissant ?
Thank you !

**Comment by ericma15** [comment]
Hey, here is  msg. Beacuse my usb 3.0 disk has just broken now.So i use a low-speed usb2.0 disk.At this time, the android subsystem failed.
https://bhpan.buaa.edu.cn:443/link/8343264312388AA9DCA38064B435ABDC
https://bhpan.buaa.edu.cn:443/link/3B13096520D3DF6945DFB677C4C1E756

**Comment by ericma15** [comment]
Hi, i do another test. I modify the chromeos_startup script in /sbin/. At the end of line. I add the
```
chmod -r 777 /mnt/stateful_partition/unencrypted/my
mount -o rw /dev/nvme0n1p4 /mnt/stateful_partition/unencrypted/my
/usr/bin/stdbuf -o0 /bin/dmesg > /mnt/stateful_partition/unencrypted/my/dmesg.txt 2>&1
/usr/bin/stdbuf -o0 /bin/echo 'a\n' > /mnt/stateful_partition/unencrypted/my/a.txt 2>&1
/usr/bin/stdbuf -o0 /bin/lsmod > /mnt/stateful_partition/unencrypted/my/lsmod.txt 2>&1
umount /mnt/stateful_partition/unencrypted/my
exit 0
```
I do this on brunch imag and croissant image. 
In croissant image, I can see these 3 files with content.
In brunch image,I see the 3 files have been establised. But all of them are 0B.
It's so strange.
BTW: the croissant i close it when show userlogin. And the brunch image reboot when it show 'Let's start it' button after chrome logo.

**Comment by sebanc** [comment]
That's a very interesting test you did here, both should work the exact same so i am not sure what happens here but that's definitely helpful. I am thinking about what other tests we could do to identify the issue.

**Comment by ericma15** [comment]
> That's a very interesting test you did here, both should work the exact same so i am not sure what happens here but that's definitely helpful. I am thinking about what other tests we could do to identify the issue.

I also doubt whether I use the wrong recovery image or the wrong cmd. I made it on the usb disk. On my another PC which with intel cpu and i915/nvidia, a optimus laptop. It behave the same,re boot.

**Comment by sebanc** [comment]
Did you try "fbcon=map:1" on the i915/nvidia one ?

**Comment by ericma15** [comment]
> Did you try "fbcon=map:1" on the i915/nvidia one ?

I add it. It now can boot. It seems that's my yoga problem.

**Comment by sebanc** [comment]
Could you adding  "console= i915.modeset=1" to the kernel command line for the one that still does not boot ?

**Comment by ericma15** [comment]
> Could you try adding "console= i915.modeset=1" to the kernel command line for the one that still does not boot ?

hey guys，i made a progress. I use a slow usb disk. So it run slowly, I change to tty2 and capture some message, some error.

**Comment by sebanc** [comment]
The udev errors are harmless, the only abnormal thing in the log is related to i915 but it might be caused by the tty2 console. Could you try the kernel command line arguments in my previous comment ?

**Comment by ericma15** [comment]
> The udev errors are harmless, the only abnormal thing in the log is related to i915 but it might be caused by the tty2 console. Could you try the kernel command line arguments in my previous comment ?

the change don't take effect. Still rebootm

**Comment by sebanc** [comment]
Could you try renaming /etc/init/udev-trigger.conf to /etc/init/udev-trigger.test and reboot ?

**Comment by ericma15** [comment]
> Could you try renaming /etc/init/udev-trigger.conf to /etc/init/udev-trigger.test and reboot ?

It doesn't reboot. Now my touchpad and touch screen not work, keyboard can.

**Comment by sebanc** [comment]
Ok so it confirms it is a module causing a kernel panic when loading

**Comment by sebanc** [comment]
Could you try probing "ideapad-laptop" first ? It might be the culpirit

**Comment by ericma15** [comment]
> Could you try probing "ideapad-laptop" first ? It might be the culpirit

I don't really understand what to do. Here is what I do: I boot in the system with udev-trigger.test. switch to tty2 and run modprobe ideapad-laptop ,seems nothing happene

**Comment by sebanc** [comment]
It's normal, it just means that it's probably not this module generating kernel panics. We would have to try the other ones that are used by your device

**Comment by ericma15** [comment]
> It's normal, it just means that it's probably not this module generating kernel panics. We would have to try the other ones that are used by your device

ok，you can give me a list. I'll try them one by one.

**Comment by sebanc** [comment]
It's the lsmod you have provided in an earlier post

**Comment by ericma15** [comment]
> It's the lsmod you have provided in an earlier post

No one cause pannic,but some mod not found.

**Comment by ericma15** [comment]
Hey, now I find udev excute rules 80-drivers.rules cause kernel panic. 
```
# do not edit this file, it will be overwritten on update

ACTION=="remove", GOTO="drivers_end"

ENV{MODALIAS}=="?*", RUN{builtin}+="kmod load $env{MODALIAS}"
SUBSYSTEM=="tifm", ENV{TIFM_CARD_TYPE}=="SD", RUN{builtin}+="kmod load tifm_sd"
SUBSYSTEM=="tifm", ENV{TIFM_CARD_TYPE}=="MS", RUN{builtin}+="kmod load tifm_ms"
SUBSYSTEM=="memstick", RUN{builtin}+="kmod load ms_block mspro_block"
SUBSYSTEM=="i2o", RUN{builtin}+="kmod load i2o_block"
SUBSYSTEM=="module", KERNEL=="parport_pc", RUN{builtin}+="kmod load ppdev"
KERNEL=="mtd*ro", ENV{MTD_FTL}=="smartmedia", RUN{builtin}+="kmod load sm_ftl"

LABEL="drivers_end"

```

So it seems some drivers cause this.

**Comment by sebanc** [comment]
Wow you are good at debuging :) So it means that with stock rootfs, if you remove this file it is working ?

**Comment by ericma15** [comment]
> Wow you are good at debuging :) So it means that with stock rootfs, if you remove this file it is working ?

No,the rule is to load kofile. Now I try to modify it to show which module it try to load.

**Comment by sebanc** [comment]
You should probably try deleting the file first and see if it boots with stock rootfs.

**Comment by ericma15** [comment]
> You should probably try deleting the file first and see if it boots with stock rootfs.

I try. Now it doesn't kernel panic.But my touchpad still can't work.

**Comment by sebanc** [comment]
I am working on touchpad right now, i hope it will be fixed in the next release. If you can identify the module responsible for the kernel panic that would be really great

**Comment by ericma15** [comment]
hey， i did it. I found all mod I should prob. Some can't find.But after I load all mods, it doesn't crash and I can use it.

**Comment by ericma15** [comment]
I found the error module is hid-sensor-cros-compat.
But I ban it in linux kernel options seems not take effect.How strange.

**Comment by ericma15** [comment]
i solve it. It seems add to kernel param can't prevent udev load it. So add it in blacklist.conf.

**Comment by sebanc** [comment]
Thank you for all the time you took to investigate this issue. 
I think i understand what the issue is now and I will try to fix it in the next release.

**Comment by ericma15** [comment]
> Thank you for all the time you took to investigate this issue.
> I think i understand what the issue is now and I will try to fix it in the next release.

Thanks what you do. Now I can use it by patch a blacklist.conf. Now there are other problem.
camera can't work.and d.process.media take two much cpu. That's what happended on my crossaint.

**Comment by sebanc** [comment]
Thanks to your investigations, i have fixed the issue in the new testing build, camera should also be fixed. Could you try it ?

**Comment by ericma15** [comment]
> Thanks to your investigations, i have fixed the issue in the new testing build, camera should also be fixed. Could you try it ?

Hey I try it. Now it can boot. Camera still can't use. Also ,  d.process.media seems take too much cpu.(This caused by chromeos mount my disk auto. It's a chromeos bug.) Also, I write a ugly patch to enable tablet mode on my laptop. But orientaion still can't work.
Here is my temporal fix.
[ideapad-laptop.txt](https://github.com/sebanc/brunch/files/4333110/ideapad-laptop.txt)

**Comment by sebanc** [comment]
Which recovery are you using ?

**Comment by ericma15** [comment]
> Which recovery are you using ?

nautilus

**Comment by sebanc** [comment]
1) Camera, do you know if it works in linux ? was it working with croissant ? Could you send a dmesg ?

2) Tablet mode, i can add your tablet mode patch, however the module that was causing the bootloops was my hid sensor compatibility module for chromeos and the investigation of the kernel panics will take time.

3) Unfortunately, i did not find how to not mount the other partitions, i was under the impression that once chromeos had finished scanning all files it was not happening anymore but maybe it is incorrect.

**Comment by ericma15** [comment]
1. Yes, other system can work.
[error_dmesg.txt](https://github.com/sebanc/brunch/files/4333207/error_dmesg.txt)
[error_lsmod.txt](https://github.com/sebanc/brunch/files/4333208/error_lsmod.txt)
message in crossaint os will be upload when I switch to that.

2. My modules is try listener then ideapad_laptop not handle message with id 10(maybe it not represent the keyboard fold back, but everytime i fold,it send.) then send key_tabletmode. This seem be right one https://github.com/lukas-w/yoga-usage-mode. But I have to anlyse my wmi.I don't know how todo.
3. That's difficult. fstab dind't take any effect. I wonder if we can write some scripts in init to unmount all folder in removable folder.

**Comment by sebanc** [comment]
1) I think both error_dmesg and error_lsmod contain the lsmod, could you repost the dmesg please ?

2) I will try to look into it.

3) Sorry but i really looked into it and did not find a solution.

**Comment by ericma15** [comment]
[upstart.log](https://github.com/sebanc/brunch/files/4333258/upstart.log)
[error_dmesg.txt](https://github.com/sebanc/brunch/files/4333259/error_dmesg.txt)

**Comment by ericma15** [comment]
Hey，I find  https://github.com/lukas-w/yoga-usage-mode is the right way to solve ideapad-yoga series(not thinkpad yoga). Now my kernel use a builtim wmi, it seems register-wmi-notifier not work well. I'll try your image later. Can you help me build  this module?

**Comment by sebanc** [comment]
I will implement a standard tablet mode notifier through sysfs triggered by udev rules which should wor for you and will be easier to maintain.

**Comment by ericma15** [comment]
That's sounds great. A universal solution is fine. Now i try to solve the iio sensor on my temp crossaint. Now i load the driver, i can see a iio:device0 in sys. Also when in tablet mode,i can read the data corect. But chromeos can't use it. I see you write hid-sensor-cros-compat. Is there some convertion to make os find the sensor? BTW, I think some 2-1 laptop is the best thing to run chrome os like surface, dell xps,lenovo yoga. And I wonder run sys from image could lead some performance problem or not?

**Comment by sebanc** [comment]
Running sys from image has been reported up until now to be the same as directly on hdd or even better in one case (see issue #14 How to update chromeos ?).

Regarding sensors, here is what I did to activate them:
- Disable chromeos sensors calibration files (easy - remove them from rootfs)
- Rename the devices in sysfs (kernel modification needed)
- Setup iio buffers (kernel modification needed)
- Convert iio values from 32 bits to 16 bits (kernel modification needed)

I don't see how you could achieve working sensors with the standard kernel hid sensors implementation but i might be wrong.

I would instead offer you that we try debugging my sensor compatibility module if you want.

**Comment by ericma15** [comment]
Ok，I will help you debugging it. Now I use a crossaint sys with fydeos 8.2 as base beause image sys take too much cpu(Chromeos mount bug). And I built a env to build kernel module. Can I try it on my crossiant? If I have to test it on image-sys, I need your kernel config. Then I can bulid and ins kernel module myself. My sensor now use `hid_sensor_accel_3d` driver.

**Comment by sebanc** [comment]
Sensors need both userspace and kernel patches, so it will be difficult to test with Croissant.

However, normaly croissant should have the same issue, how did you install it (on hdd or keep it on usb) ?

**Comment by ericma15** [comment]
I install it on HDD. I use this https://github.com/MuntashirAkon/Chrome-OS-Multiboot .there is some minor bug, I fix it manually. At this time, system don't scan other partition on my disk, so it  dosesn't have the overheat problem. Any fydeos have compiled many drivers, so my sensors can work,but chrome os doesn't  use it.

**Comment by sebanc** [comment]
Ok makes sense, in that case chromeos treats the storage as internal as its partitions are on the same block device.

The r79 branch has not been updated with the most recent changes but should be stable enough for your needs, i will try to update it with more recent changes once it is more stable.

I still think the best way to go with this would be for me to build sensor debug releases that you just test on usb.

Else, for the overheat issue you can try to create a script named "unmount.conf" in /etc/init directory with the below content:
```
start on stopped udev-trigger

script
	unmount /dev/<sdX>*
end script
```

Replace <sdX> by your block device.

**Comment by ericma15** [comment]
Ok,I'll try it.Thanks.

**Comment by sebanc** [comment]
The sensors issue has most probably been fixed in the first r80 build I have just posted. Could you confirm if your sensors work with the new build ?

**Comment by ericma15** [comment]
Hey,I try new test. In this version, camera problem fixed. Tablet mode don't take effect. Also my sensor isn't be reconginze. Even I don't find the iio bus. I try `unmount.conf` fix, it doesn't take effect.

**Comment by sebanc** [comment]
Sorry, i forgot to update you on a few things:
- to enable sensors, you now have to add "options=enable_sensors" to the kernel command line.
- for tablet mode, if it is not supported by the linux kernel, you can add "sysfs_tablet_mode" to options to be able to change tablet mode from sysfs.

Use :`
echo 1 | sudo tee /sys/bus/platform/devices/tablet_mode_switch.0/tablet_mode` to trigger tablet mode
`echo 0 | sudo tee /sys/bus/platform/devices/tablet_mode_switch.0/tablet_mode` to leave tablet mode

**Comment by sebanc** [comment]
Also if you sysfs enable "sysfs_tablet_mode", there is a file "/lib/udev/rules.d/99-tablet-mode.rules" that you can customize to trigger tablet mode events based on your keyboard vendor/product id.

**Comment by ericma15** [comment]
Thx, The sensors take effect. But my yoga computer can't see any devices changes when fold it.(In fact,when fold it,the keyboard is disabled, That's so confused.) Only I know is it will single a wmi
event. I'll try to compile the yoga-mode-useage mod.

**Comment by ericma15** [comment]
I compile the module. insmod, th log is `module verification failed: signature and/or required key missing - tainting kernel` How can I fix it.

**Comment by sebanc** [comment]
I think it is just a warning but it worked. You can confirm by running "lsmod"

**Comment by ericma15** [comment]
yes, the module worked. But chromeos don't change it.
```
localhost / # evtest /dev/input/event20
Input driver version is 1.0.1
Input device ID: bus 0x19 vendor 0x0 product 0x0 version 0x0
Input device name: "Yoga tablet switch input"
Supported events:
  Event type 0 (EV_SYN)
  Event type 5 (EV_SW)
    Event code 1 (SW_TABLET_MODE)
Properties:
Testing ... (interrupt to exit)
        ^[ Event: time 1584952141.351512, type 5 (EV_SW), code 1 (SW_TABLET_MODE), value 1
Event: time 1584952141.351512, -------------- SYN_REPORT ------------
Event: time 1584952170.926501, type 5 (EV_SW), code 1 (SW_TABLET_MODE), value 0
Event: time 1584952170.926501, -------------- SYN_REPORT ------------
Event: time 1584952178.241489, type 5 (EV_SW), code 1 (SW_TABLET_MODE), value 1
Event: time 1584952178.241489, -------------- SYN_REPORT ------------
Event: time 1584952211.961550, type 5 (EV_SW), code 1 (SW_TABLET_MODE), value 0
Event: time 1584952211.961550, -------------- SYN_REPORT ------------
```

**Comment by sebanc** [comment]
I think the module needs to be probed before boot, you can create an initscript /etc/init/tablet-mode.conf:
```
start on starting boot-services

script
	modprobe <name of the module>
end script
```

But if you are positive it works, i can just include it in the kernel.

**Comment by ericma15** [comment]
Now I can make sure the module is probe. But it seems it's report be ignored. On other system the report will cause mode change.
Also, On my archlinux ,acpid can capture the mode change event.

**Comment by sebanc** [comment]
sorry there is a mistake in my script, as the module is not built in tree you should use insmod and the complete module path.

**Comment by ericma15** [comment]
That means although I use lsmod,I can see my moudule. But it still doesn't take effect?

**Comment by sebanc** [comment]
Ah sorry i am not an expert in dkms, if it appears in lsmod then it is probed correctly

**Comment by ericma15** [comment]
Still thanks for you've have done. I think it's a great job.
here is lsmod:
```
chronos@localhost / $ lsmod| grep yoga
yoga_usage_mode        16384  0
wmi                    24576  4 intel_wmi_thunderbolt,wmi_bmof,ideapad_laptop,yoga_usage_mode
```

the module create a dev 
```
/dev/input/event7:      Yoga tablet switch input
Properties:
Testing ... (interrupt to exit)
Event: time 1584953779.693552, type 5 (EV_SW), code 1 (SW_TABLET_MODE), value 1
Event: time 1584953779.693552, -------------- SYN_REPORT ------------
Event: time 1584953804.319492, type 5 (EV_SW), code 1 (SW_TABLET_MODE), value 0
Event: time 1584953804.319492, -------------- SYN_REPORT ------------

```
module load info
```
[   17.980663] yoga_usage_mode: loading out-of-tree module taints kernel.
[   17.980707] yoga_usage_mode: module verification failed: signature and/or required key missing - tainting kernel
[   17.981135] input: Yoga tablet switch input as /devices/platform/yoga/input/input22
[   18.006488] yoga_usage_mode: Yoga tablet mode switch found, currently in laptop mode
```
```
chronos@localhost /sys/devices/platform/yoga/input/input22 $ ls
capabilities  device  event7  id  inhibited  modalias  name  phys  power  properties  subsystem  uevent  uniq
```
everything seems fine.

**Comment by sebanc** [comment]
I will include the module in the next build and i hope it will be fixed by another issue i have which could cause that.

**Comment by ericma15** [comment]
I'm appreciate you can do that.
Here is the link. https://github.com/lukas-w/yoga-usage-mode
BTW I add the `MODULE_ALIAS(wmi:06129D99-6083-4164-81AD-F092F9D773A6);`
to make it auto load. That module take effect on ideapad-yoga series laptop. Thinkpad-yoga has its office support.

**Comment by sebanc** [comment]
Btw, you have to remove "sysfs_tablet_mode" option for the standard tablet mode to work

**Comment by ericma15** [comment]
hey, I disable it. It still doesn't work. But I find something strange:
```
localhost / # evtest
No device specified, trying to scan all of /dev/input/event*
Available devices:
/dev/input/event0:      Lid Switch
/dev/input/event1:      Power Button
/dev/input/event2:      Power Button
/dev/input/event3:      AT Translated Set 2 keyboard
/dev/input/event4:      Video Bus
/dev/input/event5:      Ideapad extra buttons
/dev/input/event6:      HDA Intel PCH Mic
/dev/input/event7:      HDA Intel PCH Headphone
/dev/input/event8:      HDA Intel PCH HDMI/DP,pcm=3
/dev/input/event9:      HDA Intel PCH HDMI/DP,pcm=7
/dev/input/event10:     HDA Intel PCH HDMI/DP,pcm=8
/dev/input/event11:     HDA Intel PCH HDMI/DP,pcm=9
/dev/input/event12:     HDA Intel PCH HDMI/DP,pcm=10
/dev/input/event13:     MSFT0001:02 06CB:7F8F Touchpad
/dev/input/event14:     Wacom HID 5174 Pen
/dev/input/event15:     Wacom HID 5174 Finger
/dev/input/event19:     Yoga tablet switch input
Select the device event number [0-16]: 
```

you can see my device event is event19,but select number range is 0-16.

**Comment by ericma15** [comment]
Also when I connect a mouse, then disconnect a mouse by blutooth. the mouse device seems not removed.

**Comment by sebanc** [comment]
Hi, I have just uploaded a new build which contains your tablet mode module. Could you test it ?

**Comment by ericma15** [comment]
Thx, it now works fine.
